components/teleconsult-server/django-project/api/urls.py
from django.urls import path
from api import views
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('v1/hello/', views.HelloView.as_view(), name='hello'),
    path('v1/cases/', views.Cases.as_view(), name='api-cases-post'),
    path('v1/cases/<uuid:case_id>', views.Cases.as_view(), name='api-cases-put'),
    path('v1/cases/<uuid:case_id>/images/', views.Images.as_view(), name='api-cases-put-image'),

    path('v1/auth-token/', obtain_auth_token, name='obtain-auth-token')
]

components/teleconsult-server/django-project/core/urls.py
from core import views
from django.urls import path

urlpatterns = [
    path('create/', views.CreateCase.as_view(), name='create-case'),
    path('<uuid:pk>/', views.CaseDetail.as_view(), name='case-detail'),
    path('<uuid:pk>/report', views.PDFReport.as_view(), name='generate-pdf'),

    path('<uuid:pk>/publish', views.CreateCaseQueueItem.as_view(), name='publish-case'),
    path('<uuid:pk>/close', views.CloseCase.as_view(), name='finish-case'),
    path('<uuid:pk>/remove', views.DeleteCase.as_view(), name='remove-case'),
    path('<uuid:pk>/anamnesis/edit/', views.UpdateAnamnesis.as_view(), name='edit-anamnesis'),
    path('<uuid:pk>/finding/edit/', views.EditFinding.as_view(), name='edit-finding'),
    path('<uuid:pk>/bodystamp/edit/', views.EditBodystamp.as_view(), name='edit-bodystamp'),

    path('<uuid:pk>/images', views.AddImage.as_view(), name='add-image'),
    path('<uuid:pk>/messages', views.CreateMessage.as_view(), name='add-message'),
    path('<uuid:pk>/finding/diagnoses', views.CreateReviewDiagnosis.as_view(), name='add-finding-diagnosis'),
    path('reviewdiagnoses/<int:pk>', views.DeleteReviewDiagnosis.as_view(), name='delete-finding-diagnosis'),

    path('images/<int:pk>/delete', views.DeleteImage.as_view(), name='delete-image'),
    path('images/<int:pk>/edit', views.EditImage.as_view(), name='edit-image'),

    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('', views.CaseList.as_view(), name='case-list'),

]

components/teleconsult-server/django-project/telederm_service/urls.py
from django.urls import path, include
from users.views import LandingPageView
from django.contrib import admin
urlpatterns = [
    path('', LandingPageView.as_view(), name='landing_page'),

    path('web/users/', include('users.urls')),
    path('web/cases/', include('core.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('icd10/', include('icd10_catalog.urls')),

]

components/teleconsult-server/django-project/core/models/case_messages.py
from django.db import models


class CaseMessage(models.Model):
    case = models.ForeignKey('core.DermaConsultCase', on_delete=models.CASCADE)
    author = models.ForeignKey('users.User', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)
    message = models.CharField(max_length=512, blank=False)

components/teleconsult-server/django-project/core/models/case_queue.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class CaseQueueItem(models.Model):
    class PriorityValue(models.TextChoices):
        LOW = 'Low', _('Low')
        MEDIUM = 'Medium', _('Medium')
        HIGH = 'High', _('High')

    class QueueStatus(models.TextChoices):
        WAITING = 'Waiting', _('Waiting')
        ASSIGNED = 'Assigned', _('Assigned')
        DONE = 'Done', _('Done')

    queued_at = models.DateTimeField(auto_now=True)
    assigned_at = models.DateTimeField(blank=True, null=True)

    case = models.ForeignKey('core.DermaConsultCase', on_delete=models.CASCADE, blank=True, null=True)

    target_region = models.ForeignKey('core.Region', on_delete=models.CASCADE, null=True)

    priority = models.CharField(
        max_length=32,
        choices=PriorityValue.choices,
        default=PriorityValue.MEDIUM,
    )

    status = models.CharField(
        max_length=32,
        choices=QueueStatus.choices,
        default=QueueStatus.WAITING,
    )

    def requester(self):
        return self.case.requester

    def examiner(self):
        return self.case.examiner

    def case_id(self):
        return self.case.id

components/teleconsult-server/django-project/core/models/dermaimage.py
from django.db import models
from uuid import uuid4
from telederm_service.settings import UPLOAD_DIR_CASE_IMAGES
import base64, os, logging
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _

LOGGER = logging.getLogger(__name__)


def generate_image_upload_path(instance, filename):
    """
    This method generates the correct path for uploaded files:
    E.g. <project_root>/media/images/<case-uuid>/<image-uuid>.<extension>
    """
    instance.file_extension = filename.split('.')[-1]
    upload_path = "{}/{}.{}".format(UPLOAD_DIR_CASE_IMAGES, instance.filename, instance.file_extension)
    print(f"Generating Image upload path {upload_path}")
    return upload_path


class DermaImage(models.Model):
    uploaded_at = models.DateTimeField(auto_now=True)
    case = models.ForeignKey('core.DermaConsultCase', on_delete=models.CASCADE)
    image = models.ImageField(verbose_name=_('Image'), upload_to=generate_image_upload_path, blank=False, null=False)
    description = models.CharField(verbose_name=_('Description'), blank=True, default="", max_length=256)
    filename = models.UUIDField(default=uuid4, editable=False, auto_created=True, unique=True)

    def as_base64(self):
        if not os.path.isfile(self.image.path):
            LOGGER.error("Could not locate referenced image file while trying to convert image to base64 format!")
            return None

        with open(self.image.path, 'rb') as image_file:
            encoded_string = base64.b64encode(image_file.read()).decode('utf-8)')
            return 'data:image/%s;base64,%s' % (format, encoded_string)

    class Meta:
        permissions = (
            ('delete_image', 'Delete Image'),
        )




@receiver(post_save, sender=DermaImage)
def add_image_added_event(sender, instance=None, created=None, **kwargs):
    if created:
        from .event import Event
        Event.objects.create(case=instance.case, description=Event.EventType.IMAGE_ADDED)


@receiver(post_delete, sender=DermaImage)
def add_image_deleted_event(sender, instance=None, created=None, **kwargs):
    from .event import Event
    Event.objects.create(case=instance.case, description=Event.EventType.IMAGE_DELETED)

components/teleconsult-server/django-project/core/models/diagnosis.py
from django.db import models


class CaseDiagnosis(models.Model):
    case = models.ForeignKey('core.DermaConsultCase', on_delete=models.SET_NULL, null=True)
    diagnosis = models.ForeignKey('icd10_catalog.Icd10Item', on_delete=models.SET_NULL, null=True)

    class Meta:
        abstract = True


class ExistingDiagnosis(CaseDiagnosis):
    pass


class ReviewDiagnosis(CaseDiagnosis):
    class Meta:
        permissions = (
            ('delete_review_diagnosis', 'Delete Review Diagnosis'),
        )

components/teleconsult-server/django-project/core/models/regions.py
from django.db import models


class Region(models.Model):
    code = models.CharField(max_length=512, unique=True)
    last_regionreviewer_id = models.PositiveBigIntegerField(default=0)

    def __repr__(self):
        return self.code

    def __str__(self):
        return self.code


class RegionReviewer(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField('users.User', on_delete=models.CASCADE, null=False)
    region = models.ForeignKey('core.Region', on_delete=models.CASCADE, null=False)

components/teleconsult-server/django-project/core/views.py
import logging

from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.mixins import PermissionRequiredMixin as DjangoPermissionRequiredMixin
from django.core.exceptions import PermissionDenied
from django.urls import reverse_lazy
from django.views.generic import DetailView, TemplateView, ListView
from django.views.generic.edit import CreateView, DeleteView, UpdateView
from guardian.mixins import PermissionRequiredMixin, PermissionListMixin
from guardian.shortcuts import assign_perm
from wkhtmltopdf.views import PDFTemplateResponse

from core.forms import BodystampForm, CaseForm, ReviewDiagnosisForm
from core.models import DermaConsultCase, DermaImage, Event, CaseQueueItem, CaseMessage, ReviewDiagnosis
from core.notifications import EMailNotifier

LOG = logging.getLogger(__name__)


class Dashboard(LoginRequiredMixin, TemplateView):
    template_name = 'core/dashboard.html'


class CaseList(PermissionListMixin, ListView):
    model = DermaConsultCase
    paginate_by = 10
    permission_required = 'core.access_dermaconsultcase'


class CreateCase(DjangoPermissionRequiredMixin, CreateView):
    model = DermaConsultCase
    form_class = CaseForm
    permission_required = 'core.add_dermaconsultcase'

    def form_valid(self, form):
        case_object = form.save(commit=False)
        case_object.requester = self.request.user
        case_object.save()

        # TODO: DUPLICATED CODE FROM API/VIEWS -> Create Case logic -> probably best inside model
        assign_perm('core.access_dermaconsultcase', self.request.user, case_object)
        assign_perm('core.edit_dermaconsultcase_anamnesis', self.request.user, case_object)
        assign_perm('core.publish_dermaconsultcase', self.request.user, case_object)
        assign_perm('core.remove_dermaconsultcase', self.request.user, case_object)

        return super(CreateCase, self).form_valid(form)

    def get_success_url(self):
        return reverse_lazy('case-detail', kwargs={'pk': self.object.id})


class DeleteCase(PermissionRequiredMixin, DeleteView):
    model = DermaConsultCase
    permission_required = 'core.remove_dermaconsultcase'
    template_name = 'core/snippets/dermaconsultcase_confirm_delete.html'

    def dispatch(self, request, *args, **kwargs):
        if not self.get_object().status == DermaConsultCase.CaseStatus.REGISTERED:
            raise PermissionDenied
        else:
            return super(DeleteCase, self).dispatch(request, *args, **kwargs)

    def get_success_url(self):
        return reverse_lazy('case-list')


class CloseCase(UpdateView):
    model = DermaConsultCase
    fields = []
    template_name = 'core/close_case_confirm.html'

    def get_success_url(self):
        return reverse_lazy('case-detail', kwargs={'pk': self.object.id})

    def form_valid(self, form):
        Event.objects.create(case=self.object, description=Event.EventType.CASE_CLOSED)
        self.object.status = DermaConsultCase.CaseStatus.REVIEWED
        self.object.save()

        EMailNotifier.case_finalized(self.object)

        return super(CloseCase, self).form_valid(form)


class UpdateAnamnesis(PermissionRequiredMixin, UpdateView):
    model = DermaConsultCase
    form_class = CaseForm
    permission_required = 'core.edit_dermaconsultcase_anamnesis'
    return_403 = True

    def get_success_url(self):
        return reverse_lazy('case-detail', kwargs={'pk': self.object.id})

    def form_valid(self, form):
        Event.objects.create(case=self.object, description=Event.EventType.ANAMNESIS_REVISED)
        return super(UpdateAnamnesis, self).form_valid(form)


class CaseDetail(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = DermaConsultCase
    fields = '__all__'
    permission_required = 'core.access_dermaconsultcase'
    return_403 = True

    def get_context_data(self, **kwargs):
        context = super(CaseDetail, self).get_context_data(**kwargs)

        from django.contrib.staticfiles import finders
        from core.utils import draw_coordinates_on_image_as_base64 as draw_coords

        bodymap_image_base = finders.find('core/bodymap_big.jpg')
        painted_bodymap = draw_coords(bodymap_image_base, 326, 400, self.object.anamnesis_bodystamp_coordinates)
        context['painted_bodymap_small'] = painted_bodymap

        return context


class AddImage(LoginRequiredMixin, DjangoPermissionRequiredMixin, CreateView):
    model = DermaImage
    fields = ['image', 'description']
    permission_required = 'core.add_dermaimage'

    def get_success_url(self):
        return reverse_lazy('case-detail', kwargs={'pk': self.object.case_id})

    def form_valid(self, form):
        image = form.save(commit=False)
        case_id = self.kwargs.get('pk')
        case_object = DermaConsultCase.objects.get(pk=case_id)
        image.case = case_object

        image.save()
        user = self.request.user
        assign_perm('core.delete_image', user, image)

        return super(AddImage, self).form_valid(form)


class DeleteImage(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = DermaImage
    permission_required = 'core.delete_image'

    def get_success_url(self):
        return reverse_lazy('case-detail', kwargs={'pk': self.object.case_id})


class EditImage(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = DermaImage
    permission_required = 'core.delete_image'
    fields = ['description']

    def get_success_url(self):
        return reverse_lazy('case-detail', kwargs={'pk': self.object.case_id})


# Also serves as case publishing endpoint!
class CreateCaseQueueItem(LoginRequiredMixin, CreateView):
    model = CaseQueueItem
    fields = ['priority']

    def get_success_url(self):
        return reverse_lazy('case-detail', kwargs={'pk': self.object.case_id})

    def form_valid(self, form):
        queue_item = form.save(commit=False)
        case_id = self.kwargs.get('pk')
        case_object = DermaConsultCase.objects.get(pk=case_id)

        if not self.request.user.has_perm('core.publish_dermaconsultcase', case_object):
            raise PermissionDenied
        elif not case_object.status == DermaConsultCase.CaseStatus.REGISTERED:
            raise PermissionDenied
        else:
            queue_item.case = case_object
            queue_item.target_region = self.request.user.assigned_region
            queue_item.save()
            case_object.status = case_object.CaseStatus.PUBLISHED
            case_object.save()
            Event.objects.create(case=case_object, description=Event.EventType.CASE_PUBLISHED)

            return super(CreateCaseQueueItem, self).form_valid(form)


class CreateMessage(LoginRequiredMixin, CreateView):
    model = CaseMessage
    fields = ['message']

    # permission_required = 'core.access_dermaconsultcase'

    def get_success_url(self):
        return reverse_lazy('case-detail', kwargs={'pk': self.object.case_id})

    def form_valid(self, form):
        case_message = form.save(commit=False)
        case_id = self.kwargs.get('pk')
        case_object = DermaConsultCase.objects.get(pk=case_id)
        case_message.case = case_object
        case_message.author = self.request.user

        case_message.save()
        Event.objects.create(case=case_object, description=Event.EventType.NEW_MESSAGE)

        EMailNotifier.new_message_on_case(case_object, self.request.user)

        return super(CreateMessage, self).form_valid(form)


class EditFinding(PermissionRequiredMixin, UpdateView):
    model = DermaConsultCase
    fields = (
        'review_finding',
        'review_diagnosis',
        'review_expected_trend',
        'review_therapy_suggestion',
        'review_is_urgent',
        'review_dermatologist_visit_necessary',
    )
    permission_required = 'core.edit_dermaconsultcase_finding'
    return_403 = True

    def get_success_url(self):
        return reverse_lazy('case-detail', kwargs={'pk': self.object.id})

    def form_valid(self, form):
        Event.objects.create(case=self.object, description=Event.EventType.ANAMNESIS_REVISED)
        return super(EditFinding, self).form_valid(form)


class EditBodystamp(PermissionRequiredMixin, UpdateView):
    model = DermaConsultCase
    permission_required = 'core.edit_dermaconsultcase_anamnesis'
    return_403 = True
    template_name = 'core/bodystamp_form.html'
    form_class = BodystampForm

    def get_success_url(self):
        return reverse_lazy('case-detail', kwargs={'pk': self.object.id})

    def form_invalid(self, form):
        return super(EditBodystamp, self).form_invalid(form)

    def form_valid(self, form):
        return super(EditBodystamp, self).form_valid(form)


class PDFReport(PermissionRequiredMixin, DetailView):
    template = 'core/pdf_report.html'
    context = {}
    model = DermaConsultCase
    permission_required = 'core.access_dermaconsultcase'

    def get(self, request, *args, **kwargs):
        self.context['object'] = self.get_object()
        from django.contrib.staticfiles import finders
        from core.utils import draw_coordinates_on_image_as_base64 as draw_coords

        bodymap_image_base = finders.find('core/bodymap_big.jpg')

        painted_bodymap = draw_coords(bodymap_image_base, 326, 400, self.get_object().anamnesis_bodystamp_coordinates)

        self.context['painted_bodymap_small'] = painted_bodymap

        return PDFTemplateResponse(
            request=request,
            template=self.template,
            filename=f"OpenDermaConsult_Report_{self.get_object().id}.pdf",
            context=self.context,
            show_content_in_browser=True,
            cmd_options={
                'margin-top': 15,
                'margin-left': 15,
                'margin-right': 15,
                'margin-bottom': 15,

            }
        )


class CreateReviewDiagnosis(LoginRequiredMixin, CreateView):
    model = ReviewDiagnosis
    # fields = ['diagnosis']
    form_class = ReviewDiagnosisForm

components/teleconsult-server/django-project/core/templates/core/bodystamp_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
    <h2>{% trans 'Bodystamp' %}</h2>

    <div class="row">
        <div class="m-5 col" id="canvas_image_container" style="position:relative;">

            <img id='bodymap_image' src="{% static 'core/bodymap_big.jpg' %}" width="326" height="400"
                 style="position:absolute;z-index:1;">
            <canvas id='bodystamp_canvas' width='326' height='400' style="position:relative;z-index:20;"></canvas>

        </div>
    </div>

    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">{% trans 'Save' %} </button>

        <a href="{{ view.get_success_url }}" class="btn btn-primary">{% trans 'Cancel' %}</a>

    </form>
    <button class="btn btn-secondary border" onclick="flushCoordinates();">{% trans 'Reset' %}</button>

{% endblock %}

{% block custom_script %}
    <script src="{% static 'core/jquery-2.2.4.min.js' %}"></script>

    <script>
        {% include 'core/snippets/edit_bodystamp.js' %}
    </script>
{% endblock %}

components/teleconsult-server/django-project/core/templates/core/casemessage_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}

            <form method="post" autocomplete="off" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">{% trans 'Send' %} </button>
            </form>
    <hr>
    <a href="{% url 'case-detail' request.resolver_match.kwargs.pk %}">Back to case details</a>
{% endblock %}

components/teleconsult-server/django-project/core/templates/core/casequeueitem_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}

    <form method="post">{% csrf_token %}
        {{ form|crispy }}
        <p>Are you sure you want to publish this case?</p>
        <button type="submit" class="btn btn-primary">{% trans 'Confirm' %} </button>
        <a href="{% url 'case-detail' request.resolver_match.kwargs.pk %}" class="btn btn-primary">{% trans 'Cancel' %}</a>

    </form>
{% endblock %}

components/teleconsult-server/django-project/core/templates/core/close_case_confirm.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}

    <form method="post">{% csrf_token %}
        <p>Are you sure you want to close case "{{ object }}"?</p>
        <button type="submit" class="btn btn-primary">{% trans 'Confirm' %} </button>
        <a href="{{ view.get_success_url }}" class="btn btn-primary">{% trans 'Cancel' %}</a>
    </form>
{% endblock %}

components/teleconsult-server/django-project/core/templates/core/dashboard.html
{% extends 'base.html' %}
{% load i18n %}

{% block content %}
    <h1>Dashboard</h1>
    <ul>
    {% if user.is_general_practicioner %}
        <li><a href="{% url 'create-case' %}">{% trans 'Create a new case' %}</a><br></li>
    {% endif %}
    <li><a href="{% url 'case-list' %}">{% trans 'Go to case list' %}</a><br></li>
    </ul>
{% endblock %}

components/teleconsult-server/django-project/core/templates/core/dermaconsultcase_form.html
{% extends 'base.html' %}
{% load i18n %}

{% load crispy_forms_tags %}
{% block content %}

    <form method="post" autocomplete="off">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">{% trans 'Save' %} </button>
        <a href="{% url 'case-list' %}" class="btn btn-primary">{% trans 'Cancel' %}</a>

    </form>

{% endblock %}

components/teleconsult-server/django-project/core/templates/core/dermaconsultcase_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block custom_css %}
    <style>
        .table-hover > tbody > tr:hover {
            background-color: #cce5ff;
        }

        #caseIdOverflow {
            overflow: hidden;
            white-space: nowrap;
            text-overflow: ellipsis;
            width: 10ch;
            display: inline-block;
        }

    </style>
{% endblock %}
{% block content %}
    <h1>{% trans 'My Cases' %}</h1>


    <table class="table table-bordered table-hover table-sm table-striped">
        <thead>
        <tr>
            <th>{% trans 'Case ID' %}</th>
            <th>{% trans 'Registered at' %}</th>
            <th>
                {% if request.user.is_dermatologist %}
                    {% trans 'Requested by' %}
                {% else %}
                    {% trans 'Examiner' %}
                {% endif %}
            </th>
            <th colspan="2">{% trans 'Last update' %}</th>
            <th>{% trans 'Case status' %}</th>
        </tr>
        </thead>
        <tbody>
        {% for dermaconsultcase in page_obj %}
            {% with dermaconsultcase as case %}
                <tr onclick="window.location='{% url 'case-detail' case.id %}';" style="cursor: pointer;">

                    <td><span id="caseIdOverflow" data-toggle="tooltip"
                              title="{{ case.id }}" class="text-monospace text-uppercase">#{{ case.id }}</span></td>
                    <td>{{ case.created_at|date:"d.m.Y, H:i" }}</td>
                    <td>
                        {% if request.user.is_dermatologist %}
                            {% if case.requester.medical_title|length > 0 %}
                                {{ case.requester.medical_title }} {% endif %}{{ case.requester.first_name }}
                            {{ case.requester.last_name }}
                        {% else %}
                            {% if case.examiner %}
                                {% if case.examiner.medical_title|length > 0 %}
                                    {{ case.examiner.medical_title }} {% endif %}{{ case.examiner.first_name }}
                                {{ case.examiner.last_name }}
                            {% else %}
                                {% trans 'No examiner assigned yet' %}
                            {% endif %}
                        {% endif %}
                    </td>
                    <td>{{ case.get_last_event.timestamp|date:"d.m.Y, H:i" }}</td>
                    <td>{{ case.get_last_event.get_description_display }}</td>
                    <td><b>{{ case.get_status_display }}</b></td>

                </tr>
            {% endwith %}
        {% endfor %}
        </tbody>
    </table>

    {% if is_paginated %}
        <nav  aria-label="pagination nav" class="d-flex justify-content-left">
            <ul class="pagination">
                {% if page_obj.has_previous %}
                    <li class="page-item"><a class="page-link"
                                             href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
                {% else %}
                    <li class="page-item disabled"><span class="page-link">&laquo;</span></li>
                {% endif %}
                {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                        <li class="page-item active"><span class="page-link">{{ i }} <span
                                class="sr-only">(current)</span></span></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
                    {% endif %}
                {% endfor %}
                {% if page_obj.has_next %}
                    <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">&raquo;</a>
                    </li>
                {% else %}
                    <li class="page-item disabled"><span class="page-link">&raquo;</span></li>
                {% endif %}
            </ul>
        </nav>
    {% endif %}

{% endblock %}

components/teleconsult-server/django-project/core/templates/core/dermaimage_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}

    <form method="post">{% csrf_token %}
        <p>Are you sure you want to delete "{{ object }}"?</p>
        <button type="submit" class="btn btn-primary">{% trans 'Confirm' %} </button>
        <a href="{{ view.get_success_url }}" class="btn btn-primary">{% trans 'Cancel' %}</a>
    </form>
{% endblock %}

components/teleconsult-server/django-project/core/templates/core/dermaimage_form.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}

            <form method="post" autocomplete="off" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-primary">{% trans 'Upload' %} </button>
            </form>
    <hr>

{% endblock %}

components/teleconsult-server/django-project/core/templates/core/reviewdiagnosis_confirm_delete.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block content %}

    <form method="post">{% csrf_token %}
        <p>{% trans 'Are you sure you want to delete' %} "{{ object.diagnosis }}"?</p>
        <button type="submit" class="btn btn-primary">{% trans 'Confirm' %} </button>
        <a href="{{ view.get_success_url }}" class="btn btn-primary">{% trans 'Cancel' %}</a>
    </form>
{% endblock %}

components/teleconsult-server/django-project/core/templates/core/reviewdiagnosis_form.html
{% extends 'base.html' %}
{# Don't forget that one ! #}
{% load static %}
{% load crispy_forms_tags %}

{% block content %}
<div>
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <table style="display: none">
            {{ view.formset.empty_form }}
        </table>

        <table>
            {{ view.formset }}
        </table>

        <span id="add-form" class="button">Submit</span>

        <input type="submit" />
    </form>
</div>
{% endblock %}

{% block custom_script %}
<script type="text/javascript" src="{% static 'admin/js/vendor/jquery/jquery.js' %}"></script>

{{ form.media }}

<script>
(function($) {
    $('#add-form').click(function() {
        var index = $('#id_diagnosis-TOTAL_FORMS').val()
        var newTable = $('#id_diagnosis-__prefix__-DELETE').parents('table').clone()
        newTable.find(':input').each(function() {
            for (attr of ['name', 'id'])
                $(this).attr(
                    attr,
                    $(this).attr(attr).replace('__prefix__', index)
                )
        })
        newTable.insertBefore($(this))
        $('#id_diagnosis-TOTAL_FORMS').val(
            parseInt($('#id_diagnosis-TOTAL_FORMS').val()) + 1
        )
        newTable.slideDown()
    })
})($)
</script>
{% endblock %}