components/teleconsult-server/django-project/api/urls.py
from django.urls import path
from api import views
from rest_framework.authtoken.views import obtain_auth_token

urlpatterns = [
    path('v1/hello/', views.HelloView.as_view(), name='hello'),
    path('v1/cases/', views.Cases.as_view(), name='api-cases-post'),
    path('v1/cases/<uuid:case_id>', views.Cases.as_view(), name='api-cases-put'),
    path('v1/cases/<uuid:case_id>/images/', views.Images.as_view(), name='api-cases-put-image'),

    path('v1/auth-token/', obtain_auth_token, name='obtain-auth-token')
]

components/teleconsult-server/django-project/core/urls.py
from core import views
from django.urls import path

urlpatterns = [
    path('create/', views.CreateCase.as_view(), name='create-case'),
    path('<uuid:pk>/', views.CaseDetail.as_view(), name='case-detail'),
    path('<uuid:pk>/report', views.PDFReport.as_view(), name='generate-pdf'),

    path('<uuid:pk>/publish', views.CreateCaseQueueItem.as_view(), name='publish-case'),
    path('<uuid:pk>/close', views.CloseCase.as_view(), name='finish-case'),
    path('<uuid:pk>/remove', views.DeleteCase.as_view(), name='remove-case'),
    path('<uuid:pk>/anamnesis/edit/', views.UpdateAnamnesis.as_view(), name='edit-anamnesis'),
    path('<uuid:pk>/finding/edit/', views.EditFinding.as_view(), name='edit-finding'),
    path('<uuid:pk>/bodystamp/edit/', views.EditBodystamp.as_view(), name='edit-bodystamp'),

    path('<uuid:pk>/images', views.AddImage.as_view(), name='add-image'),
    path('<uuid:pk>/messages', views.CreateMessage.as_view(), name='add-message'),
    path('<uuid:pk>/finding/diagnoses', views.CreateReviewDiagnosis.as_view(), name='add-finding-diagnosis'),
    path('reviewdiagnoses/<int:pk>', views.DeleteReviewDiagnosis.as_view(), name='delete-finding-diagnosis'),

    path('images/<int:pk>/delete', views.DeleteImage.as_view(), name='delete-image'),
    path('images/<int:pk>/edit', views.EditImage.as_view(), name='edit-image'),

    path('dashboard/', views.Dashboard.as_view(), name='dashboard'),
    path('', views.CaseList.as_view(), name='case-list'),

]

components/teleconsult-server/django-project/telederm_service/urls.py
from django.urls import path, include
from users.views import LandingPageView
from django.contrib import admin
urlpatterns = [
    path('', LandingPageView.as_view(), name='landing_page'),

    path('web/users/', include('users.urls')),
    path('web/cases/', include('core.urls')),
    path('api/', include('api.urls')),
    path('admin/', admin.site.urls),
    path('icd10/', include('icd10_catalog.urls')),

]

components/teleconsult-server/django-project/core/models/case_messages.py
from django.db import models


class CaseMessage(models.Model):
    case = models.ForeignKey('core.DermaConsultCase', on_delete=models.CASCADE)
    author = models.ForeignKey('users.User', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)
    message = models.CharField(max_length=512, blank=False)

components/teleconsult-server/django-project/core/models/case_queue.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class CaseQueueItem(models.Model):
    class PriorityValue(models.TextChoices):
        LOW = 'Low', _('Low')
        MEDIUM = 'Medium', _('Medium')
        HIGH = 'High', _('High')

    class QueueStatus(models.TextChoices):
        WAITING = 'Waiting', _('Waiting')
        ASSIGNED = 'Assigned', _('Assigned')
        DONE = 'Done', _('Done')

    queued_at = models.DateTimeField(auto_now=True)
    assigned_at = models.DateTimeField(blank=True, null=True)

    case = models.ForeignKey('core.DermaConsultCase', on_delete=models.CASCADE, blank=True, null=True)

    target_region = models.ForeignKey('core.Region', on_delete=models.CASCADE, null=True)

    priority = models.CharField(
        max_length=32,
        choices=PriorityValue.choices,
        default=PriorityValue.MEDIUM,
    )

    status = models.CharField(
        max_length=32,
        choices=QueueStatus.choices,
        default=QueueStatus.WAITING,
    )

    def requester(self):
        return self.case.requester

    def examiner(self):
        return self.case.examiner

    def case_id(self):
        return self.case.id

components/teleconsult-server/django-project/core/models/dermaconsultcase.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _
from multiselectfield import MultiSelectField
from guardian.shortcuts import assign_perm
from telederm_service.settings import LOGGER
from uuid import uuid4
from core.notifications import EMailNotifier


class DermaConsultCase(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid4, editable=False, auto_created=True)

    class CaseStatus(models.TextChoices):
        REGISTERED = 'Registered', _('Registered')
        PUBLISHED = 'Published', _('Published')
        IN_REVIEW = 'In Review', _('In Review')
        REVIEWED = 'Reviewed', _('Reviewed')

    class SexValue(models.TextChoices):
        MALE = 'M', _('Male')
        FEMALE = 'F', _('Female')

    class DermaComplaint(models.TextChoices):
        ITCHES = 'itches', _('itches')
        BURNS = 'burns', _('burns')
        WEEPS = 'weeps', _('weeps')
        HURTS = 'hurts', _('hurts')
        BLEEDS = 'bleeds', _('bleeds')

    class ComplaintDuration(models.TextChoices):
        DAYS = 'days', _('days')
        WEEKS = 'weeks', _('weeks')
        MONTHS = 'months', _('months')
        YEARS = 'years', _('years')

    class YesNoChoice(models.TextChoices):
        YES = 'yes', _('Yes')
        NO = 'no', _('No')

    requester = models.ForeignKey('users.User', on_delete=models.CASCADE, related_name='requesting_gp')
    examiner = models.ForeignKey('users.User', on_delete=models.CASCADE, null=True, blank=True,
                                 related_name='assigned_dermatologist')
    status = models.CharField(verbose_name=_("Case Status"), max_length=16, choices=CaseStatus.choices,
                              default=CaseStatus.REGISTERED,
                              blank=False, null=False)

    created_at = models.DateTimeField(auto_now_add=True)

    anamnesis_patient_age = models.IntegerField(verbose_name=_("Patient's age"), blank=True, null=False, default=18)
    anamnesis_patient_sex = models.CharField(verbose_name=_("Patient's sex"), max_length=16, choices=SexValue.choices,
                                             default=SexValue.MALE,
                                             blank=True, null=False)
    anamnesis_patient_occupation = models.CharField(verbose_name=_("Patient's occupation"), blank=True, max_length=256)
    anamnesis_finding = models.TextField(verbose_name=_("GP's finding"), blank=True)
    anamnesis_localisation = models.TextField(verbose_name=_("Localisation"), blank=True)
    anamnesis_current_medication = models.TextField(verbose_name=_("Current medication"), blank=True)
    anamnesis_existing_diagnoses = models.TextField(verbose_name=_("Existing diagnoses"), blank=True)
    anamnesis_complaint_type = MultiSelectField(verbose_name=_("Type of complaint"), choices=DermaComplaint.choices,
                                                blank=True)
    anamnesis_complaint_duration = models.CharField(verbose_name=_("Duration of complaint"), max_length=32,
                                                    choices=ComplaintDuration.choices, blank=True)
    anamnesis_specific_question = models.TextField(verbose_name=_("Specific question"), blank=True)

    anamnesis_bodystamp_coordinates = models.JSONField(verbose_name=_("Bodystamp Coordinates"), default=list,
                                                       blank=True)

    review_finding = models.TextField(verbose_name=_("Dermatologist's finding"), default="", blank=False)
    review_diagnosis = models.TextField(verbose_name=_("Diagnosis"), default="", blank=False)
    review_expected_trend = models.TextField(verbose_name=_("Expected trend"), default="", blank=True)
    review_therapy_suggestion = models.TextField(verbose_name=_("Suggested therapy"), default="", blank=True)

    review_is_urgent = models.CharField(max_length=64, verbose_name=_('Case is urgent'), choices=YesNoChoice.choices,
                                        default=YesNoChoice.NO,
                                        blank=False)
    review_dermatologist_visit_necessary = models.CharField(max_length=64,
                                                            verbose_name=_('Visit at dermatologist necessary'),
                                                            choices=YesNoChoice.choices, default=YesNoChoice.NO,
                                                            blank=False)

    class Meta:
        permissions = (
            ('access_dermaconsultcase', 'Can access dermaconsultcase'),
            ('edit_dermaconsultcase_anamnesis', 'Can edit anamnesis of dermaconsultcase'),
            ('edit_dermaconsultcase_finding', 'Can edit finding of dermaconsultcase'),
            ('publish_dermaconsultcase', 'Can publish case'),
            ('close_dermaconsultcase', 'Can close case'),
            ('remove_dermaconsultcase', 'Can remove case')

        )
        ordering = ['-created_at']

    def get_events(self):
        from .event import Event
        return Event.objects.filter(case_id=self.id)

    def get_last_event(self):
        from .event import Event
        return Event.objects.filter(case_id=self.id).last()

    def get_images(self):
        from .dermaimage import DermaImage
        return DermaImage.objects.filter(case_id=self.id).order_by('-uploaded_at')

    def get_messages(self):
        from .case_messages import CaseMessage
        return CaseMessage.objects.filter(case_id=self.id).order_by('-timestamp')

    def get_review_diagnoses(self):
        from .diagnosis import ReviewDiagnosis
        return ReviewDiagnosis.objects.filter(case_id=self.id)

    def assign_to_reviewer(self, user):
        self.examiner = user
        assign_perm('core.access_dermaconsultcase', user, self)
        assign_perm('core.edit_dermaconsultcase_finding', user, self)
        assign_perm('core.close_dermaconsultcase', user, self)

        from .event import Event
        Event.objects.create(case=self, description=Event.EventType.REVIEWER_ASSIGNED)
        self.status = self.CaseStatus.IN_REVIEW
        self.save()

        # TODO: probably all emails should be triggered from model
        EMailNotifier.case_in_review_for_gp(self)
        EMailNotifier.case_in_review_for_dermatologist(self)

    def update_patient_data(self, patient_age: int, patient_sex: str):
        self.anamnesis_patient_age = patient_age
        self.anamnesis_patient_sex = patient_sex
        from .event import Event
        Event.objects.create(case=self, description=Event.EventType.PATIENT_DATA_UPDATED)
        self.save()


@receiver(post_save, sender=DermaConsultCase)
def add_created_event(sender, instance=None, created=None, **kwargs):
    if created:
        from .event import Event
        Event.objects.create(case=instance)

components/teleconsult-server/django-project/core/models/dermaimage.py
from django.db import models
from uuid import uuid4
from telederm_service.settings import UPLOAD_DIR_CASE_IMAGES
import base64, os, logging
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.utils.translation import gettext_lazy as _

LOGGER = logging.getLogger(__name__)


def generate_image_upload_path(instance, filename):
    """
    This method generates the correct path for uploaded files:
    E.g. <project_root>/media/images/<case-uuid>/<image-uuid>.<extension>
    """
    instance.file_extension = filename.split('.')[-1]
    upload_path = "{}/{}.{}".format(UPLOAD_DIR_CASE_IMAGES, instance.filename, instance.file_extension)
    print(f"Generating Image upload path {upload_path}")
    return upload_path


class DermaImage(models.Model):
    uploaded_at = models.DateTimeField(auto_now=True)
    case = models.ForeignKey('core.DermaConsultCase', on_delete=models.CASCADE)
    image = models.ImageField(verbose_name=_('Image'), upload_to=generate_image_upload_path, blank=False, null=False)
    description = models.CharField(verbose_name=_('Description'), blank=True, default="", max_length=256)
    filename = models.UUIDField(default=uuid4, editable=False, auto_created=True, unique=True)

    def as_base64(self):
        if not os.path.isfile(self.image.path):
            LOGGER.error("Could not locate referenced image file while trying to convert image to base64 format!")
            return None

        with open(self.image.path, 'rb') as image_file:
            encoded_string = base64.b64encode(image_file.read()).decode('utf-8)')
            return 'data:image/%s;base64,%s' % (format, encoded_string)

    class Meta:
        permissions = (
            ('delete_image', 'Delete Image'),
        )




@receiver(post_save, sender=DermaImage)
def add_image_added_event(sender, instance=None, created=None, **kwargs):
    if created:
        from .event import Event
        Event.objects.create(case=instance.case, description=Event.EventType.IMAGE_ADDED)


@receiver(post_delete, sender=DermaImage)
def add_image_deleted_event(sender, instance=None, created=None, **kwargs):
    from .event import Event
    Event.objects.create(case=instance.case, description=Event.EventType.IMAGE_DELETED)

components/teleconsult-server/django-project/core/models/diagnosis.py
from django.db import models


class CaseDiagnosis(models.Model):
    case = models.ForeignKey('core.DermaConsultCase', on_delete=models.SET_NULL, null=True)
    diagnosis = models.ForeignKey('icd10_catalog.Icd10Item', on_delete=models.SET_NULL, null=True)

    class Meta:
        abstract = True


class ExistingDiagnosis(CaseDiagnosis):
    pass


class ReviewDiagnosis(CaseDiagnosis):
    class Meta:
        permissions = (
            ('delete_review_diagnosis', 'Delete Review Diagnosis'),
        )

components/teleconsult-server/django-project/core/models/event.py
from django.db import models
from django.utils.translation import gettext_lazy as _


class Event(models.Model):
    class EventType(models.TextChoices):
        CREATED = 'CR', _('Case Created')
        PATIENT_DATA_UPDATED = 'PU', _('Patient data updated')
        ANAMNESIS_REVISED = 'AR', _('Anamnesis Revised')
        FINDING_REVISED = 'FR', _('Finding Revised')
        IMAGE_ADDED = 'IA', _('Image Added')
        IMAGE_DELETED = 'ID', _('Image Deleted')
        CASE_PUBLISHED = 'CP', _('Case Published')
        NEW_MESSAGE = 'NM', _('New Message')
        REVIEWER_ASSIGNED = 'RA', _('Reviewer Assigned')
        CASE_CLOSED = 'CC', _('Case Closed')

    description = models.CharField(
        max_length=2,
        choices=EventType.choices,
        default=EventType.CREATED,
    )
    case = models.ForeignKey('core.DermaConsultCase', on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now=True)

components/teleconsult-server/django-project/core/models/regions.py
from django.db import models


class Region(models.Model):
    code = models.CharField(max_length=512, unique=True)
    last_regionreviewer_id = models.PositiveBigIntegerField(default=0)

    def __repr__(self):
        return self.code

    def __str__(self):
        return self.code


class RegionReviewer(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.OneToOneField('users.User', on_delete=models.CASCADE, null=False)
    region = models.ForeignKey('core.Region', on_delete=models.CASCADE, null=False)

components/teleconsult-server/django-project/core/forms.py
from django.forms import ModelForm, HiddenInput, TextInput, ModelChoiceField
from core.models import DermaConsultCase, ReviewDiagnosis
from icd10_catalog.models import Icd10Item
from dal import autocomplete


class CaseForm(ModelForm):
    class Meta:
        model = DermaConsultCase
        fields = [
            'anamnesis_patient_age',
            'anamnesis_patient_sex',
            'anamnesis_patient_occupation',
            'anamnesis_finding',
            'anamnesis_localisation',
            'anamnesis_current_medication',
            'anamnesis_existing_diagnoses',
            'anamnesis_complaint_type',
            'anamnesis_complaint_duration',
            'anamnesis_specific_question',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['anamnesis_finding'].required = True
        self.fields['anamnesis_specific_question'].required = True
        self.fields['anamnesis_patient_age'].required = True
        self.fields['anamnesis_patient_sex'].required = True


class BodystampForm(ModelForm):
    class Meta:
        model = DermaConsultCase
        fields = ['anamnesis_bodystamp_coordinates']
        widgets = {'anamnesis_bodystamp_coordinates': HiddenInput()}


class ReviewDiagnosisForm(ModelForm):
    diagnosis = ModelChoiceField(
        queryset=Icd10Item.objects.all(),
        widget=autocomplete.ModelSelect2(
            url='icd-10-lookup',
            attrs={
                # Set some placeholder
                'data-placeholder': 'Autocomplete ...',
                # Only trigger autocompletion after 3 characters have been typed
                'data-minimum-input-length': 3,
                'width': '100%',
            },
        )
    )

    class Meta:
        model = ReviewDiagnosis
        fields = ('diagnosis',)

components/teleconsult-server/django-project/core/templates/core/snippets/anamnesis_detail.html
{% load get_field_verbose_name %}
{% load i18n %}

<div class="container">
    <div style="float: right;">

        {% include 'core/snippets/existing_diagnoses.html' %}

        {% include 'core/snippets/bodystamp.html' %}
    </div>
    <div class="content">
        <div class="d-flex justify-content-between">
            <h4>{% trans 'Anamnesis' %}
                {% if request.user.is_general_practicioner and object.status != object.CaseStatus.REVIEWED %}
                    <a href="{% url 'edit-anamnesis' object.id %}"><i class="fa fa-edit"></i></a>
                {% endif %}
            </h4>

        </div>

        <dt>{% trans 'Patient' %}:</dt>
        <dd>{{ case.anamnesis_patient_age }}, {{ case.get_anamnesis_patient_sex_display }}</dd>
        {% if case.anamnesis_patient_occupation %}
            <dd>{{ case.anamnesis_patient_occupation }}</dd>
        {% endif %}

        <dt>{% get_field_verbose_name case 'anamnesis_finding' %}:</dt>
        <dd>{{ case.anamnesis_finding }}</dd>

        {% if case.anamnesis_localisation %}
            <dt>{% get_field_verbose_name case 'anamnesis_localisation' %}:</dt>
            <dd>{{ case.anamnesis_localisation }}</dd>
        {% endif %}

        {% if case.anamnesis_current_medication %}
            <dt>{% get_field_verbose_name case 'anamnesis_current_medication' %}:</dt>
            <dd>{{ case.anamnesis_current_medication }}</dd>
        {% endif %}

        {% if case.anamnesis_existing_diagnoses %}
            <dt>{% get_field_verbose_name case 'anamnesis_existing_diagnoses' %}:</dt>
            <dd>{{ case.anamnesis_existing_diagnoses }}</dd>
        {% endif %}

        {% if case.anamnesis_complaint_type %}
            <dt>{% get_field_verbose_name case 'anamnesis_complaint_type' %}:</dt>
            <dd>{{ case.anamnesis_complaint_type }}</dd>
        {% endif %}

        {% if case.anamnesis_complaint_duration %}
            <dt>{% get_field_verbose_name case 'anamnesis_complaint_duration' %}:</dt>
            <dd>{{ case.get_anamnesis_complaint_duration_display }}</dd>
        {% endif %}

        <dt>{% get_field_verbose_name case 'anamnesis_specific_question' %}:</dt>
        <dd>{{ case.anamnesis_specific_question }}</dd>

    </div>
</div>

components/teleconsult-server/django-project/core/templates/core/snippets/bodystamp.html
{% load i18n %}
{% load static %}

<div class="d-flex justify-content-between">

    <h4>{% trans 'Bodystamp' %}

        {% if request.user.is_general_practicioner and object.status != object.CaseStatus.REVIEWED %}
            <a href="{% url 'edit-bodystamp' object.id %}"><i class="fa fa-edit"></i></a>
        {% endif %}
    </h4>
</div>

<div class="img-magnifier-container">
    <!--<img id="bodystamp_image" src="{% static "core/bodymap_small.jpg" %}" width="100%" alt="Bodymap" class="zoom"
         data-magnify-src="{% static "core/bodymap_big.jpg" %}">-->
    <img id="bodystamp_image" src="{{ painted_bodymap_small }}" width="100%" alt="Bodymap" class="zoom"
         data-magnify-src="{{ painted_bodymap_small }}">
</div>

components/teleconsult-server/django-project/core/templates/core/snippets/case_diagnoses.html
{% load i18n %}


<div class="d-flex justify-content-between">

    <h4>{% trans 'Diagnoses' %}
        {% if request.user.is_dermatologist and object.status != object.CaseStatus.REVIEWED %}
            <a href="{% url 'add-finding-diagnosis' object.id %}"><i class="fa fa-plus-circle"></i></a>
        {% endif %}
    </h4>


</div>

<table class="table table-sm table-bordered">

    {% for item in object.get_review_diagnoses %}
        <tr>
            <td>{{ item.diagnosis.code }}</td>
            <td>{{ item.diagnosis.description }}</td>
            {% if object.status != object.CaseStatus.REVIEWED %}

                {% if request.user.is_dermatologist %}
                    <td>
                        <a class="badge badge-warning" href="{% url 'delete-finding-diagnosis' item.id %}">
                            <i class="fa fa-trash"> </i>
                        </a>
                    </td>
                {% endif %}

            {% endif %}
        </tr>
    {% endfor %}
</table>

components/teleconsult-server/django-project/core/templates/core/snippets/case_events.html
{% load i18n %}

<h5>{% trans 'Case History' %}</h5>
{% for event in object.get_events %}
    <span class="badge badge-light">{{ event.timestamp }}: {{ event.get_description_display }}</span>
    <br>
{% endfor %}

components/teleconsult-server/django-project/core/templates/core/snippets/case_images.html
{% load i18n %}



    <h4>{% trans 'Attachments' %}

    {% if request.user.is_general_practicioner and object.status != object.CaseStatus.REVIEWED %}
        <a href="{% url 'add-image' object.id %}"><i
                class="fa fa-plus-circle"></i></a></h4>
    {% endif %}



{% if object.get_images %}
    <table class="table table-sm table-hover" >
        <thead>
        <tr>
            <th scope="col">{% trans 'Image ID' %}</th>
            <th scope="col">{% trans 'Timestamp' %}</th>
            <th scope="col">{% trans 'Description' %}</th>
            <th scope="col">{% trans 'Thumbnail' %}</th>
            {% if object.status != object.CaseStatus.REVIEWED %}
                {% if request.user.is_general_practicioner %}
                    <th scope="col"></th>
                {% endif %}
            {% endif %}

        </tr>
        </thead>
        <tbody>
        {% for image_object in object.get_images %}
            <tr>
                <th scope="row">{{ image_object.id }}</th>
                <td>{{ image_object.uploaded_at }}</td>
                <td>{{ image_object.description }}
                    {% if object.status != object.CaseStatus.REVIEWED %}
                        {% if request.user.is_general_practicioner %}
                            <a href="{% url 'edit-image' image_object.id %}"><i class="fa fa-edit"></i></a>
                        {% endif %}
                    {% endif %}
                </td>
                <td style="text-align: center;">
                    <img id="modalImage_{{ image_object.id }}" class="modalImage"
                         alt="{{ image_object.description }}" src="{{ image_object.as_base64 }}"
                         style="width:100px" onclick="openModal({{ image_object.id }});">
                </td>
                {% if object.status != object.CaseStatus.REVIEWED %}
                    <td>
                        {% if request.user.is_general_practicioner %}
                            <h5>
                                <a class="badge badge-warning" href="{% url 'delete-image' image_object.id %}">
                                    <i class="fa fa-trash"> </i>
                                </a>
                            </h5>
                        {% endif %}
                    </td>
                {% endif %}
            </tr>

        {% endfor %}

        </tbody>
    </table>
    <!-- The Modal -->
    <div id="myModal" class="modal">

        <!-- The Close Button -->
        <span class="close">&times;</span>

        <!-- Modal Content (The Image) -->
        <img class="modal-content" id="modal_image_content">

        <!-- Modal Caption (Image Text) -->
        <div id="caption"></div>
    </div>
{% else %}
    {% trans 'No attachments yet' %}
{% endif %}

components/teleconsult-server/django-project/core/templates/core/snippets/case_messages.html
{% load i18n %}


<h5>{% trans 'Messages' %}
    {% if object.status == object.CaseStatus.IN_REVIEW %}
        <a href="{% url 'add-message' object.id %}"><i class="fa fa-plus-circle"></i></a>
    {% endif %}
</h5>

{% if object.get_messages %}
    {% for case_message in object.get_messages %}
        <small><b><u>{% if case_message.author.medical_title|length > 0 %}
            {{ case_message.author.medical_title }} {% endif %} {{ case_message.author.last_name }}, {{ case_message.timestamp|date:"d.m.Y, H:i" }}:</u></b></small>
        <br>
        <small> {{ case_message.message }}</small>
        <br>
    {% endfor %}
{% else %}
    <small> {% trans 'No messages yet' %} </small>
{% endif %}

components/teleconsult-server/django-project/core/templates/core/snippets/qr_code.html
{% load qr_code %}

{% qr_from_text object.id size="5" image_format="png" error_correction="L" %}

components/teleconsult-server/django-project/core/templates/core/snippets/review_detail.html
{% load get_field_verbose_name %}
{% load i18n %}

<div class="container">
    <div style="float: right;">
        {% include 'core/snippets/case_diagnoses.html' %}
    </div>
    <div class="content">

        <div class="d-flex justify-content-between">
            <h4>{% trans 'Finding' %}
                {% if request.user.is_dermatologist and object.status == object.CaseStatus.IN_REVIEW %}
                    <a href="{% url 'edit-finding' object.id %}"><i class="fa fa-edit"></i></a>
                {% endif %}
            </h4>
        </div>

        <dt>{% get_field_verbose_name case 'review_finding' %}:</dt>
        <dd>
            {% if case.review_finding|length > 0 %}
                {{ case.review_finding }}
            {% else %}
                {% trans 'No finding available yet' %}
            {% endif %}
        </dd>

        {% if case.review_diagnosis %}
            <dt>{% get_field_verbose_name case 'review_diagnosis' %}:</dt>
            <dd>{{ case.review_diagnosis }}</dd>
        {% endif %}

        {% if case.review_expected_trend %}
            <dt>{% get_field_verbose_name case 'review_expected_trend' %}:</dt>
            <dd>{{ case.review_expected_trend }}</dd>
        {% endif %}

        {% if case.review_therapy_suggestion %}
            <dt>{% get_field_verbose_name case 'review_therapy_suggestion' %}:</dt>
            <dd>{{ case.review_therapy_suggestion }}</dd>
        {% endif %}

        {% if case.review_is_urgent %}
            <dt>{% get_field_verbose_name case 'review_is_urgent' %}:</dt>
            <dd>{{ case.get_review_is_urgent_display }}</dd>
        {% endif %}

        {% if case.review_dermatologist_visit_necessary %}
            <dt>{% get_field_verbose_name case 'review_dermatologist_visit_necessary' %}:</dt>
            <dd>{{ case.get_review_dermatologist_visit_necessary_display }}</dd>
        {% endif %}
    </div>
</div>

components/teleconsult-server/django-project/core/templates/core/snippets/status_progressbar.html
<div class="progress" style="height: 20px;">
    {% if case.status == object.CaseStatus.REGISTERED %}
        <div class="progress-bar progress-bar-striped" style="width:25%">
    {% elif case.status == object.CaseStatus.PUBLISHED %}
        <div class="progress-bar progress-bar-striped" style="width:50%">
    {% elif case.status == object.CaseStatus.IN_REVIEW %}
        <div class="progress-bar progress-bar-striped" style="width:75%">
    {% elif case.status == object.CaseStatus.REVIEWED %}
        <div class="progress-bar progress-bar-striped" style="width:100%">
    {% endif %}
    <b>{{ case.get_status_display }}</b>
    </div>
    </div>